language: java
script: mvn clean verify
jdk:
  - oraclejdk8

before_script:
    - "mysql -e 'create database database_contact;'"
    - "mysql -e 'create table database_contact.contacts (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));'"
    - "mysql -e 'insert into database_contact.contacts (name) VALUES (\"Albert\");'"

script: mvn install

after_failure:
    - "mysql -e 'show databases;'"
    - "cat ./config/database.yml"
    - "bundle exec rake --version"
